### ISSUE TITLE
Home screen icon

### ISSUE THREAD

**Issue by joehonywill** [MashSoftware/the-button#23]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem, just a preference

**Describe the solution you'd like**
I've added a shortcut to my iPhone home screen. The icon is a small, clipped screenshot and not a nice snazzy icon - is that something that heroku supports?

**Comment by matthew-shaw** [comment]
Ahh yes, I had considered this. The site needs a favicon anyway so I can provide multiple resolutions for iOS and Android devices too. Good suggestion!
