### ISSUE TITLE
Accept 120 entry limit once

### ISSUE THREAD

**Issue by flynnbops** [MashSoftware/the-button#27]
**Is your feature request related to a problem? Please describe.**
Once we've exceeded 120 entries, we get the attached message. The ability to acknowledge the deletion of entries once, would mean I don't need to see the message more than needed.

**Describe the solution you'd like**
Would like the ability to "accept" the message once, and not see it again.

**Describe alternatives you've considered**
Thought about deleting older entries, but is totally redundant.

**Additional context**
![image](https://user-images.githubusercontent.com/16778356/98563842-903f1900-22a3-11eb-9982-712fbe18aa4a.png)

**Comment by matthew-shaw** [comment]
Thanks for your feedback @flynnbops. However, this alert will no longer be present after moving to a time window based retention mechanism. I.e. a scheduled job will remove all entries older than a certain age, say 3 months. The user will not be informed on each entry page load, only in their account page. I plan to develop this in the next couple of releases.
