### ISSUE TITLE
Total time does not include currently running task

### ISSUE THREAD

**Issue by ahosgood** [MashSoftware/the-button#43]
**Describe the bug**
In the weekly summary on the left, it is stated that I have 4 time entries (one of these is in progress) - this is correct.
The total time so far does not take this currently running task into consideration and provides only the total of the completed tasks.

**To reproduce**
Start a task and check the weekly summary pane.

**Expected behavior**
Either the number of time entries listed needs to not include the current running task (in this example, 3 rather than 4)
[OR]
The total time for the week needs to include the current running task (in this example, 24.23 rather than 17.71)

**Screenshots**
<img width="1340" alt="Screenshot 2021-01-20 at 15 31 13" src="https://user-images.githubusercontent.com/2356642/105198356-7c325600-5b35-11eb-9556-56954503519d.png">

**Environment**
Mac OS, Chrome 87 - although I believe this is a serverside issue.

**Comment by matthew-shaw** [comment]
@ahosgood your assumption is correct the total time is that of completed entries only and doesn't include the duration of any in-progress entries. #42 covers this already but thanks for noticing and raising.
