### ISSUE TITLE
Editing a time entry on Chrome results in Internal Server Error

### ISSUE THREAD

**Issue by mattgirdler** [MashSoftware/the-button#6]
**Describe the bug**
Editing a time entry on Chrome results in Internal Server Error due to lack of seconds input

**To Reproduce**
1. Open the app in Chrome
2. Click on Edit Entry
3. Enter a date/time

**Expected behavior**
Date time entry to be updated

**Screenshots**
Form input:
<img width="616" alt="Screenshot 2019-04-29 at 08 57 36" src="https://user-images.githubusercontent.com/11294853/56882942-1c407580-6a5d-11e9-841f-c00826c24106.png">

Error page:
<img width="343" alt="Screenshot 2019-04-29 at 08 57 46" src="https://user-images.githubusercontent.com/11294853/56882955-2498b080-6a5d-11e9-99a8-0c35fc99f008.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome

**Comment by matthew-shaw** [comment]
Seems to be Chrome stripping the seconds off the timestamp. Since the field is marked up as a `datetime-local` HTLM5 field, Chome decides to provide a handy datetime picker control, which doesn't allow you to over-type the seconds in. I should have validated this on the backend of course.

**Comment by matthew-shaw** [comment]
Editing times in Chrome resulted in an error due to the `datetime-local` picker tool removing seconds. Changed inputs to `text` type rather than HTML5 `datetime-local` to improve compatibility at the expense of browser/device native pickers. Needs further investigation to improve user experience.
